apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: node-18624 
  janus-idp.io/tekton: node-18624
  backstage.io/kubernetes-id: node-18624
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: node-18624
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  